/**
 * Validates Semark signatures and the source-comment policy.
 *
 * @remarks
 * Responsibility: Reports structural Semark violations through the Oxlint rule API.
 *
 * Boundary: Examines TypeScript syntax and comments but does not judge semantic accuracy or naming quality.
 *
 * @semarkFile
 */

import {
  defineRule,
  type Comment,
  type Context,
  type ESTree,
  type Ranged,
} from "@oxlint/plugins";
import {
  TSDocConfiguration,
  TSDocParser,
  TSDocTagDefinition,
  TSDocTagSyntaxKind,
} from "@microsoft/tsdoc";

type SemarkCategory =
  | "COMMENT_UNAUTHORIZED"
  | "FILE_SIGNATURE_FORMAT"
  | "FILE_SIGNATURE_MISSING"
  | "FILE_SIGNATURE_POSITION"
  | "LENGTH_LIMIT"
  | "METHOD_SIGNATURE_FORMAT"
  | "METHOD_SIGNATURE_MISSING"
  | "TAG_ORDER_INVALID"
  | "TSDOC_INVALID";

interface SemarkFinding {
  category: SemarkCategory;
  problem: string;
}

interface CallableRecord {
  anchor: ESTree.Node;
  callable: ESTree.Function | ESTree.ArrowFunctionExpression;
}

const allowedMethodTags = [
  "@typeParam",
  "@param",
  "@returns",
  "@throws",
  "@deprecated",
  "@example",
  "@see",
] as const;

const allowedRemarksLabels = [
  "Side effects:",
  "Invariant:",
  "Constraint:",
  "Assumption:",
  "Interaction:",
] as const;

const approvedDirectivePatterns = [
  /^\/\s*<reference\s+(?:path|types|lib|no-default-lib)=/u,
  /^\/\s*<amd-(?:module|dependency)\b/u,
  /^@ts-(?:check|nocheck|ignore|expect-error)\b/u,
  /^(?:eslint|oxlint)-(?:disable|enable)(?:-line|-next-line)?\b/u,
  /^(?:c8|v8)\s+ignore\b/u,
  /^istanbul\s+ignore\b/u,
  /^(?:prettier|oxfmt)-ignore\b/u,
  /^SPDX-License-Identifier:/u,
  /^@(?:license|preserve)\b/u,
  /^@generated\b/u,
  /^(?:Generated by|This file is generated|DO NOT EDIT)\b/iu,
] as const;

const semarkFileTagDefinition = new TSDocTagDefinition({
  tagName: "@semarkFile",
  syntaxKind: TSDocTagSyntaxKind.ModifierTag,
});
const tsdocConfiguration = new TSDocConfiguration();
tsdocConfiguration.addTagDefinition(semarkFileTagDefinition);
const tsdocParser = new TSDocParser(tsdocConfiguration);

/**
 * Reports one Semark finding at a source range.
 *
 * @param context - The active Oxlint rule context.
 * @param target - The range that caused the finding.
 * @param finding - The stable category and problem text.
 * @returns Nothing.
 */
function reportFinding(context: Context, target: Ranged, finding: SemarkFinding): void {
  context.report({
    message: `${finding.category}: ${finding.problem}`,
    node: target,
  });
}

/**
 * Tests whether Semark applies to the current filename.
 *
 * @param filename - The absolute source filename from Oxlint.
 * @returns True for hand-authored TypeScript source extensions.
 */
function isApplicableTypeScriptFile(filename: string): boolean {
  return (
    /\.(?:cts|mts|ts|tsx)$/u.test(filename) &&
    !/\.d\.(?:cts|mts|ts)$/u.test(filename)
  );
}

/**
 * Removes JSDoc decoration from each comment line.
 *
 * @param comment - The block comment to normalize.
 * @returns Comment lines without leading JSDoc markers.
 */
function getDocLines(comment: Comment): string[] {
  const lines = comment.value.split(/\r?\n/u).map((line) =>
    line.replace(/^\s*\*\s?/u, "").trimEnd(),
  );

  while (lines[0] === "") {
    lines.shift();
  }

  while (lines.at(-1) === "") {
    lines.pop();
  }

  return lines;
}

/**
 * Counts natural-language words in signature text.
 *
 * @param text - The signature text to count.
 * @returns The number of words in the text.
 */
function countWords(text: string): number {
  return text.match(/[\p{L}\p{N}][\p{L}\p{N}'/-]*/gu)?.length ?? 0;
}

/**
 * Counts terminal sentence marks in one summary.
 *
 * @param text - The summary text to inspect.
 * @returns The number of terminal sentence marks.
 */
function countSentences(text: string): number {
  return text.match(/[.!?](?:["')\]]|$)/gu)?.length ?? 0;
}

/**
 * Gets nonempty lines from a normalized signature.
 *
 * @param lines - The normalized signature lines.
 * @returns The lines that contain text.
 */
function getNonemptyLines(lines: readonly string[]): string[] {
  return lines.filter((line) => line.trim().length > 0);
}

/**
 * Validates one comment with the configured TSDoc parser.
 *
 * @param comment - The JSDoc comment to parse.
 * @returns The first parser finding, or null when the syntax is valid.
 */
function validateTSDocSyntax(comment: Comment): SemarkFinding | null {
  const parserContext = tsdocParser.parseString(`/*${comment.value}*/`);
  const message = parserContext.log.messages[0];

  if (message === undefined) {
    return null;
  }

  return {
    category: "TSDOC_INVALID",
    problem: message.unformattedText,
  };
}

/**
 * Gets one paragraph from normalized signature lines.
 *
 * @param lines - The normalized signature lines.
 * @param startIndex - The index of the paragraph's first line.
 * @returns The paragraph text through the next blank line.
 */
function getParagraph(lines: readonly string[], startIndex: number): string {
  const paragraphLines: string[] = [];

  for (let index = startIndex; index < lines.length; index += 1) {
    const line = lines[index];
    if (line === undefined || line.trim() === "") {
      break;
    }
    paragraphLines.push(line);
  }

  return paragraphLines.join(" ");
}

/**
 * Tests one paragraph against sentence and word limits.
 *
 * @param lines - The normalized signature lines.
 * @param startIndex - The index of the paragraph's first line.
 * @param maximumWords - The permitted word count.
 * @param maximumSentences - The permitted sentence count.
 * @returns True when the paragraph exceeds either limit.
 */
function paragraphExceedsLimits(
  lines: readonly string[],
  startIndex: number,
  maximumWords: number,
  maximumSentences: number,
): boolean {
  const paragraph = getParagraph(lines, startIndex);
  return countWords(paragraph) > maximumWords || countSentences(paragraph) > maximumSentences;
}

/**
 * Validates the required file-signature structure and limits.
 *
 * @param comment - The file signature comment.
 * @returns All structural findings for the signature.
 */
function validateFileSignature(comment: Comment): SemarkFinding[] {
  const findings: SemarkFinding[] = [];
  const lines = getDocLines(comment);
  const nonemptyLines = getNonemptyLines(lines);
  const summary = nonemptyLines[0] ?? "";
  const tsdocFinding = validateTSDocSyntax(comment);
  const remarksIndex = lines.indexOf("@remarks");
  const responsibilityIndex = lines.findIndex((line) => line.startsWith("Responsibility: "));
  const boundaryIndex = lines.findIndex((line) => line.startsWith("Boundary: "));
  const semarkFileIndex = lines.indexOf("@semarkFile");

  if (tsdocFinding !== null) {
    findings.push(tsdocFinding);
  }

  if (!comment.value.trimStart().startsWith("*")) {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Use a JSDoc block for the file signature.",
    });
  }

  if (summary.startsWith("@") || countSentences(summary) !== 1) {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Start with one purpose sentence.",
    });
  }

  if (countWords(summary) > 25) {
    findings.push({
      category: "LENGTH_LIMIT",
      problem: "Keep the file purpose to 25 words at most.",
    });
  }

  if (!nonemptyLines.includes("@remarks")) {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Add the @remarks block.",
    });
  }

  if (
    remarksIndex === -1 ||
    responsibilityIndex <= remarksIndex ||
    boundaryIndex <= responsibilityIndex ||
    semarkFileIndex <= boundaryIndex
  ) {
    findings.push({
      category: "TAG_ORDER_INVALID",
      problem: "Use the required file-signature paragraph and tag order.",
    });
  }

  if (!nonemptyLines.some((line) => line.startsWith("Responsibility: "))) {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Add the Responsibility paragraph.",
    });
  }

  if (!nonemptyLines.some((line) => line.startsWith("Boundary: "))) {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Add the Boundary paragraph.",
    });
  }

  if (
    (responsibilityIndex !== -1 &&
      paragraphExceedsLimits(lines, responsibilityIndex, 50, 2)) ||
    (boundaryIndex !== -1 && paragraphExceedsLimits(lines, boundaryIndex, 50, 2))
  ) {
    findings.push({
      category: "LENGTH_LIMIT",
      problem: "Keep each required file-signature paragraph to two sentences and 50 words at most.",
    });
  }

  const fileTags = nonemptyLines.filter((line) => line.startsWith("@"));
  if (
    fileTags.length !== 2 ||
    fileTags[0] !== "@remarks" ||
    fileTags[1] !== "@semarkFile"
  ) {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Use only @remarks and @semarkFile in a file signature.",
    });
  }

  if (nonemptyLines.at(-1) !== "@semarkFile") {
    findings.push({
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Put @semarkFile at the end of the signature.",
    });
  }

  if (countWords(lines.join(" ")) > 120) {
    findings.push({
      category: "LENGTH_LIMIT",
      problem: "Keep the complete file signature to 120 words at most.",
    });
  }

  return findings;
}

/**
 * Gets the ordered method tags from a normalized signature.
 *
 * @param lines - The normalized signature lines.
 * @returns Tags that start a signature line.
 */
function getMethodTags(lines: readonly string[]): string[] {
  return lines
    .map((line) => line.match(/^(@\S+)/u)?.[1])
    .filter((tag): tag is string => tag !== undefined && tag !== "@remarks");
}

/**
 * Tests whether method tags use the required order.
 *
 * @param tags - The ordered tags from a method signature.
 * @returns True when each tag is permitted and ordered.
 */
function methodTagsHaveValidOrder(tags: readonly string[]): boolean {
  let previousIndex = -1;

  for (const tag of tags) {
    const tagIndex = allowedMethodTags.indexOf(
      tag as (typeof allowedMethodTags)[number],
    );

    if (tagIndex < previousIndex || tagIndex === -1) {
      return false;
    }

    previousIndex = tagIndex;
  }

  return true;
}

/**
 * Tests whether remarks labels use the required order.
 *
 * @param lines - The normalized signature lines.
 * @returns True when each remarks label is permitted and ordered.
 */
function remarksLabelsHaveValidOrder(lines: readonly string[]): boolean {
  let previousIndex = -1;

  for (const line of lines) {
    const labelIndex = allowedRemarksLabels.findIndex((label) => line.startsWith(label));

    if (labelIndex === -1) {
      continue;
    }

    if (labelIndex < previousIndex) {
      return false;
    }

    previousIndex = labelIndex;
  }

  return true;
}

/**
 * Validates the required method-signature structure and limits.
 *
 * @param comment - The method signature comment.
 * @param callable - The callable that the signature documents.
 * @returns All structural findings for the signature.
 */
function validateMethodSignature(
  comment: Comment,
  callable: ESTree.Function | ESTree.ArrowFunctionExpression,
): SemarkFinding[] {
  const findings: SemarkFinding[] = [];
  const lines = getDocLines(comment);
  const nonemptyLines = getNonemptyLines(lines);
  const summary = nonemptyLines[0] ?? "";
  const tags = getMethodTags(lines);
  const tsdocFinding = validateTSDocSyntax(comment);

  if (tsdocFinding !== null) {
    findings.push(tsdocFinding);
  }

  if (!comment.value.trimStart().startsWith("*")) {
    findings.push({
      category: "METHOD_SIGNATURE_FORMAT",
      problem: "Use a JSDoc block for the method signature.",
    });
  }

  if (summary.startsWith("@") || countSentences(summary) !== 1) {
    findings.push({
      category: "METHOD_SIGNATURE_FORMAT",
      problem: "Start with one behavior sentence.",
    });
  }

  if (countWords(summary) > 25) {
    findings.push({
      category: "LENGTH_LIMIT",
      problem: "Keep the method summary to 25 words at most.",
    });
  }

  if (nonemptyLines.includes("@semarkFile")) {
    findings.push({
      category: "METHOD_SIGNATURE_FORMAT",
      problem: "Do not use @semarkFile in a method signature.",
    });
  }

  if (!methodTagsHaveValidOrder(tags) || !remarksLabelsHaveValidOrder(lines)) {
    findings.push({
      category: "TAG_ORDER_INVALID",
      problem: "Use the required remarks-label and tag order.",
    });
  }

  const remarksIndex = lines.indexOf("@remarks");
  const firstMethodTagIndex = lines.findIndex((line) =>
    allowedMethodTags.some((tag) => line.startsWith(tag)),
  );
  if (remarksIndex !== -1 && firstMethodTagIndex !== -1 && remarksIndex > firstMethodTagIndex) {
    findings.push({
      category: "TAG_ORDER_INVALID",
      problem: "Put @remarks before method tags.",
    });
  }

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (
      allowedRemarksLabels.some((label) => line.startsWith(label)) &&
      paragraphExceedsLimits(lines, index, 50, 2)
    ) {
      findings.push({
        category: "LENGTH_LIMIT",
        problem: "Keep each remarks paragraph to two sentences and 50 words at most.",
      });
      break;
    }
  }

  const parameterTagCount = tags.filter((tag) => tag === "@param").length;
  if (parameterTagCount !== callable.params.length) {
    findings.push({
      category: "METHOD_SIGNATURE_FORMAT",
      problem: "Document each runtime parameter with one @param tag.",
    });
  }

  const typeParameterCount = callable.typeParameters?.params.length ?? 0;
  const typeParameterTagCount = tags.filter((tag) => tag === "@typeParam").length;
  if (typeParameterTagCount !== typeParameterCount) {
    findings.push({
      category: "METHOD_SIGNATURE_FORMAT",
      problem: "Document each type parameter with one @typeParam tag.",
    });
  }

  for (const line of lines) {
    const parameterDescription = line.match(/^@(typeParam|param)\s+\S+\s+-\s+(.+)$/u)?.[2];
    const resultDescription = line.match(/^@(returns|throws)\s+(.+)$/u)?.[2];
    const description = parameterDescription ?? resultDescription;

    if (description !== undefined && countWords(description) > 30) {
      findings.push({
        category: "LENGTH_LIMIT",
        problem: "Keep each parameter, return, or failure description to 30 words at most.",
      });
      break;
    }
  }

  if (countWords(lines.join(" ")) > 200) {
    findings.push({
      category: "LENGTH_LIMIT",
      problem: "Keep the complete method signature to 200 words at most.",
    });
  }

  return findings;
}

/**
 * Gets the declaration node that owns a callable signature.
 *
 * @param node - The callable or declaration node to inspect.
 * @returns The node that a method signature must precede.
 */
function getSignatureAnchor(node: ESTree.Node): ESTree.Node {
  let anchor = node;

  if (anchor.type === "VariableDeclarator") {
    anchor = anchor.parent;
  }

  const parent = anchor.parent;
  if (
    parent !== null &&
    (parent.type === "ExportNamedDeclaration" || parent.type === "ExportDefaultDeclaration")
  ) {
    anchor = parent;
  }

  return anchor;
}

/**
 * Gets the JSDoc block immediately before a declaration.
 *
 * @param context - The active Oxlint rule context.
 * @param anchor - The declaration that owns the signature.
 * @returns The adjacent JSDoc comment, or null when none exists.
 */
function getAdjacentDocComment(context: Context, anchor: ESTree.Node): Comment | null {
  const comments = context.sourceCode.getCommentsBefore(anchor);
  const comment = comments.at(-1);

  if (
    comment === undefined ||
    comment.type !== "Block" ||
    !comment.value.trimStart().startsWith("*")
  ) {
    return null;
  }

  return comment;
}

/**
 * Tests whether a function has an implementation body.
 *
 * @param callable - The function or arrow function to inspect.
 * @returns True when the callable contains executable statements.
 */
function hasImplementationBody(
  callable: ESTree.Function | ESTree.ArrowFunctionExpression,
): boolean {
  return callable.body?.type === "BlockStatement";
}

/**
 * Validates one callable and records its signature comment.
 *
 * @param context - The active Oxlint rule context.
 * @param record - The callable and its signature anchor.
 * @param callableStarts - Source offsets for callables that already received validation.
 * @param signatureStarts - Source offsets for recognized method signatures.
 * @returns Nothing.
 */
function validateCallableRecord(
  context: Context,
  record: CallableRecord,
  callableStarts: Set<number>,
  signatureStarts: Set<number>,
): void {
  if (!hasImplementationBody(record.callable) || callableStarts.has(record.callable.start)) {
    return;
  }

  callableStarts.add(record.callable.start);
  const anchor = getSignatureAnchor(record.anchor);
  const signature = getAdjacentDocComment(context, anchor);

  if (signature === null) {
    reportFinding(context, anchor, {
      category: "METHOD_SIGNATURE_MISSING",
      problem: "Add a method signature immediately before this callable.",
    });
    return;
  }

  signatureStarts.add(signature.start);
  for (const finding of validateMethodSignature(signature, record.callable)) {
    reportFinding(context, signature, finding);
  }
}

/**
 * Tests whether a comment uses an approved directive form.
 *
 * @param comment - The source comment to classify.
 * @returns True for recognized compiler, tooling, license, or generated-code directives.
 */
function isApprovedDirective(comment: Comment): boolean {
  if (comment.type === "Shebang") {
    return true;
  }

  const normalizedText = comment.value
    .split(/\r?\n/u)
    .map((line) => line.replace(/^\s*\*\s?/u, "").trim())
    .filter((line) => line.length > 0);

  return normalizedText.some((line) =>
    approvedDirectivePatterns.some((pattern) => pattern.test(line)),
  );
}

/**
 * Validates the file signature and records its comment.
 *
 * @param context - The active Oxlint rule context.
 * @param program - The TypeScript program node.
 * @param signatureStarts - Source offsets for recognized file signatures.
 * @returns Nothing.
 */
function validateProgramFileSignature(
  context: Context,
  program: ESTree.Program,
  signatureStarts: Set<number>,
): void {
  const fileSignatures = context.sourceCode
    .getAllComments()
    .filter((comment) => comment.value.includes("@semarkFile"));

  if (fileSignatures.length === 0) {
    reportFinding(context, program, {
      category: "FILE_SIGNATURE_MISSING",
      problem: "Add one file signature before the first source statement.",
    });
    return;
  }

  const signature = fileSignatures[0];
  if (signature === undefined) {
    return;
  }

  for (const fileSignature of fileSignatures) {
    signatureStarts.add(fileSignature.start);
  }

  if (fileSignatures.length > 1) {
    reportFinding(context, fileSignatures[1] ?? signature, {
      category: "FILE_SIGNATURE_FORMAT",
      problem: "Keep exactly one file signature in each applicable file.",
    });
  }

  const firstStatement = program.body[0];
  if (firstStatement !== undefined && signature.end > firstStatement.start) {
    reportFinding(context, signature, {
      category: "FILE_SIGNATURE_POSITION",
      problem: "Put the file signature before the first source statement.",
    });
  }

  for (const finding of validateFileSignature(signature)) {
    reportFinding(context, signature, finding);
  }
}

/**
 * Reports comments that are not signatures or approved directives.
 *
 * @param context - The active Oxlint rule context.
 * @param signatureStarts - Source offsets for all recognized signatures.
 * @returns Nothing.
 */
function validateAuthorizedComments(context: Context, signatureStarts: Set<number>): void {
  for (const comment of context.sourceCode.getAllComments()) {
    if (signatureStarts.has(comment.start) || isApprovedDirective(comment)) {
      continue;
    }

    reportFinding(context, comment, {
      category: "COMMENT_UNAUTHORIZED",
      problem: "Remove this comment or convert it to a Semark signature or approved directive.",
    });
  }
}

export const semarkValidationRule = defineRule({
  meta: {
    type: "problem",
    docs: {
      description: "Require Semark signatures and approved source comments.",
      recommended: true,
      url: "https://github.com/bearfire-dev/semark-protocol",
    },
    schema: false,
  },

  /**
   * Creates the Semark validation visitors for one source file.
   *
   * @param context - The active Oxlint rule context.
   * @returns Visitors that validate file, callable, and comment boundaries.
   */
  create(context) {
    const callableStarts = new Set<number>();
    const signatureStarts = new Set<number>();
    const applies = isApplicableTypeScriptFile(context.filename);

    return {
      /**
       * Validates the file signature before callable traversal starts.
       *
       * @param program - The parsed TypeScript program.
       * @returns Nothing.
       */
      Program(program) {
        if (applies) {
          validateProgramFileSignature(context, program, signatureStarts);
        }
      },

      /**
       * Validates one function declaration.
       *
       * @param node - The function declaration to validate.
       * @returns Nothing.
       */
      FunctionDeclaration(node) {
        if (applies) {
          validateCallableRecord(
            context,
            { anchor: node, callable: node },
            callableStarts,
            signatureStarts,
          );
        }
      },

      /**
       * Validates one class method implementation.
       *
       * @param node - The class method to validate.
       * @returns Nothing.
       */
      MethodDefinition(node) {
        if (applies && node.type === "MethodDefinition") {
          validateCallableRecord(
            context,
            { anchor: node, callable: node.value },
            callableStarts,
            signatureStarts,
          );
        }
      },

      /**
       * Validates one callable variable initializer.
       *
       * @param node - The variable declarator to inspect.
       * @returns Nothing.
       */
      VariableDeclarator(node) {
        if (
          applies &&
          (node.init?.type === "FunctionExpression" ||
            node.init?.type === "ArrowFunctionExpression")
        ) {
          validateCallableRecord(
            context,
            { anchor: node, callable: node.init },
            callableStarts,
            signatureStarts,
          );
        }
      },

      /**
       * Validates one callable class property.
       *
       * @param node - The class property to inspect.
       * @returns Nothing.
       */
      PropertyDefinition(node) {
        if (
          applies &&
          (node.value?.type === "FunctionExpression" ||
            node.value?.type === "ArrowFunctionExpression")
        ) {
          validateCallableRecord(
            context,
            { anchor: node, callable: node.value },
            callableStarts,
            signatureStarts,
          );
        }
      },

      /**
       * Validates one callable object property.
       *
       * @param node - The object property to inspect.
       * @returns Nothing.
       */
      Property(node) {
        if (applies && node.parent.type === "ObjectExpression") {
          const objectProperty = node as ESTree.ObjectProperty;
          if (
            objectProperty.value.type === "FunctionExpression" ||
            objectProperty.value.type === "ArrowFunctionExpression"
          ) {
            validateCallableRecord(
              context,
              { anchor: objectProperty, callable: objectProperty.value },
              callableStarts,
              signatureStarts,
            );
          }
        }
      },

      /**
       * Validates one arrow-function callback.
       *
       * @param node - The arrow function to inspect.
       * @returns Nothing.
       */
      ArrowFunctionExpression(node) {
        if (
          applies &&
          node.parent.type !== "VariableDeclarator" &&
          node.parent.type !== "PropertyDefinition" &&
          node.parent.type !== "Property"
        ) {
          validateCallableRecord(
            context,
            { anchor: node, callable: node },
            callableStarts,
            signatureStarts,
          );
        }
      },

      /**
       * Validates one function-expression callback.
       *
       * @param node - The function expression to inspect.
       * @returns Nothing.
       */
      FunctionExpression(node) {
        if (
          applies &&
          node.parent.type !== "MethodDefinition" &&
          node.parent.type !== "VariableDeclarator" &&
          node.parent.type !== "PropertyDefinition" &&
          node.parent.type !== "Property"
        ) {
          validateCallableRecord(
            context,
            { anchor: node, callable: node },
            callableStarts,
            signatureStarts,
          );
        }
      },

      /**
       * Validates the remaining comments after callable traversal ends.
       *
       * @param _program - The completed TypeScript program.
       * @returns Nothing.
       */
      "Program:exit"(_program) {
        if (applies) {
          validateAuthorizedComments(context, signatureStarts);
        }
      },
    };
  },
});
